"""Ingest python variables — generated by `make new-ingestion NAME=python_variables`.

Usage:
    uv run python scripts/ingestion/python_variables.py [--force]

Options:
    --force   Re-ingest all chunks even if already present (incremental=False)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Allow running as a script from the repo root.
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from src.adapters.web_adapter import WebAdapter  # noqa: E402
from src.config.settings import settings  # noqa: E402
from src.domain.ingest_pipeline import IngestPipeline  # noqa: E402
from src.vector.embedding_client import EmbeddingClient  # noqa: E402
from src.vector.qdrant_client import QdrantAdapter  # noqa: E402


# ---------------------------------------------------------------------------
# 1. Configure the pipeline
# ---------------------------------------------------------------------------
qdrant    = QdrantAdapter(host=settings.qdrant_host, port=settings.qdrant_port)
embedding = EmbeddingClient(url=settings.embedding_url)
pipeline  = IngestPipeline(qdrant=qdrant, embedding=embedding)


# ---------------------------------------------------------------------------
# 2. Define the source(s)
# ---------------------------------------------------------------------------
def build_chunks() -> list:
    adapter = WebAdapter()
    return adapter.ingest(
        path_or_url="https://www.w3schools.com/python/python_variables_names.asp",  # TODO: set real URL
        metadata={
            "origin":      "W3Schools",  # TODO
            "source_type": "standard",              # policy | standard | catalog
            "domain":      "engineering",            # security | compliance | engineering | …
            "version_ref": "v1.0.0",              # TODO
            "timestamp":   "2024-01-01",          # TODO: ISO date of the source
        },
    )


# ---------------------------------------------------------------------------
# 3. Run
# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true",
                        help="Force re-ingest (disables incremental mode)")
    args = parser.parse_args()

    chunks = build_chunks()
    result = pipeline.run(chunks, incremental=not args.force)

    if result.errors:
        print(f"⚠  {len(result.errors)} error(s):")
        for err in result.errors:
            print(f"   • {err}")

    print(f"\n✓  ingested={result.ingested}  skipped={result.skipped}  errors={len(result.errors)}")
    if result.errors:
        sys.exit(1)


if __name__ == "__main__":
    main()
