#!/usr/bin/env python3
"""Scaffold a new ingestion script from the template.

Usage (via make):
    make new-ingestion NAME=ingest_container_policy
    make new-ingestion NAME=ingest_iso27001 ADAPTER=pdf DOMAIN=compliance

Usage (direct):
    uv run python scripts/new_ingestion.py <name> [--adapter ADAPTER] [--domain DOMAIN]

Adapters: markdown (default), pdf, git, web
Domains:  security (default), compliance, engineering, data-governance, legal
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

TEMPLATE = Path(__file__).parent / "ingestion" / "_template.py"
OUTPUT_DIR = Path(__file__).parent / "ingestion"

ADAPTER_IMPORTS = {
    "markdown": "from src.adapters.markdown_adapter import MarkdownAdapter",
    "pdf":      "from src.adapters.pdf_adapter import PdfAdapter",
    "git":      "from src.adapters.git_adapter import GitAdapter",
    "web":      "from src.adapters.web_adapter import WebAdapter",
}

ADAPTER_CLASS = {
    "markdown": "MarkdownAdapter",
    "pdf":      "PdfAdapter",
    "git":      "GitAdapter",
    "web":      "WebAdapter",
}

ADAPTER_INGEST_ARGS = {
    "markdown": '        path="path/to/source.md",   # TODO: set real path',
    "pdf":      '        path="path/to/source.pdf",  # TODO: set real path',
    "git": (
        '        repo_path="path/to/repo",    # TODO: set real path\n'
        '        branch="main",\n'
        '        glob_pattern="**/*.md",       # TODO: adjust glob'
    ),
    "web":      '        url="https://example.com/policy",  # TODO: set real URL',
}

SOURCE_TYPE_FOR_DOMAIN = {
    "security":        "policy",
    "compliance":      "standard",
    "engineering":     "standard",
    "data-governance": "policy",
    "legal":           "policy",
}


def slugify(name: str) -> str:
    """Ensure the name is a valid Python identifier / filename."""
    slug = re.sub(r"[^a-z0-9_]", "_", name.lower().strip())
    if not slug or slug[0].isdigit():
        slug = "ingest_" + slug
    return slug


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("name", help="Script name (e.g. ingest_container_policy)")
    parser.add_argument("--adapter", default="markdown",
                        choices=["markdown", "pdf", "git", "web"],
                        help="Source adapter to use (default: markdown)")
    parser.add_argument("--domain", default="security",
                        choices=["security", "compliance", "engineering",
                                 "data-governance", "legal"],
                        help="Governance domain (default: security)")
    args = parser.parse_args()

    name = slugify(args.name)
    adapter = args.adapter
    domain = args.domain
    source_type = SOURCE_TYPE_FOR_DOMAIN[domain]

    output_path = OUTPUT_DIR / f"{name}.py"
    if output_path.exists():
        print(f"✗  {output_path} already exists — aborting.")
        sys.exit(1)

    template = TEMPLATE.read_text()

    # Replace adapter import
    template = template.replace(
        "from src.adapters.markdown_adapter import MarkdownAdapter  # noqa: E402 — change adapter as needed",
        f"{ADAPTER_IMPORTS[adapter]}  # noqa: E402",
    )

    # Replace adapter instantiation
    template = template.replace(
        "    adapter = MarkdownAdapter()  # TODO: swap adapter / source path as needed",
        f"    adapter = {ADAPTER_CLASS[adapter]}()",
    )

    # Replace ingest call path arg
    template = template.replace(
        '        path="path/to/source.md",   # TODO: set real path',
        ADAPTER_INGEST_ARGS[adapter],
    )

    # Update metadata defaults
    template = template.replace('"path/to/source.md"', f'"<{name}_source>"')
    template = template.replace('"policy"', f'"{source_type}"')
    template = template.replace('"security"', f'"{domain}"')

    # Update docstring header
    template = template.replace(
        'Ingestion script template — generated by `make new-ingestion NAME=<name>`.',
        f'Ingest {name.replace("_", " ")} — generated by `make new-ingestion NAME={name}`.',
    )
    template = template.replace(
        "scripts/ingestion/<name>.py",
        f"scripts/ingestion/{name}.py",
    )

    output_path.write_text(template)
    print(f"✓  Created {output_path}")
    print(f"   adapter={adapter}  domain={domain}  source_type={source_type}")
    print(f"\n   Next steps:")
    print(f"   1. Edit {output_path} — set the real path/URL and metadata")
    print(f"   2. uv run python {output_path} --force   (first run)")
    print(f"   3. uv run python {output_path}            (incremental re-runs)")


if __name__ == "__main__":
    main()
